name: Build and Deploy Hugo site (user site)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
          extended: true

      - name: Build Hugo
        run: hugo --minify --destination .

      - name: Remove non-site files
        run: |
          rm -rf content/ themes/ layouts/ .github/ config.* resources/ archetypes/ static/ README.md

      - name: Commit and push site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy site" || echo "No changes to commit"
          git push
