name: Build and Deploy Hugo site (User Site)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --destination .

      - name: Remove non-site files
        run: |
          rm -rf content/ themes/ layouts/ resources/ .github/ config.* README.md
